Kurzdokumentation von Caltabiano und Wolf
th-koeln/mi-bachelor-screendesign-projekte pull request #3
Opened 2021-03-19 18:00 UTC by Splashpixx

2021-03-19 19:19 UTC, finnge requested changes
Nur Dateiname von Style-Guide anpassen. Sonst alles ok!

2021-03-19 19:19 UTC, finnge commented on _kurzdokus/sd-2020/Caltabiano-Wolf.md
> +styleguide: Wolf-Caltabiano-Styleguide-Patternlab.svg
Könnt Ihr beim Styleguide gleiche Reihenfolge der Nachnamen wie bei den anderen Artefakten wählen. Dann ist das bei mehr Gruppen nicht unübersichtlich im Dateiverzeichnis

2021-03-20 17:55 UTC, Splashpixx commented on _kurzdokus/sd-2020/Caltabiano-Wolf.md
> +styleguide: Wolf-Caltabiano-Styleguide-Patternlab.svg
Änderung wurde durchgeführt

2021-03-21 10:18 UTC, finnge approved these changes

2021-03-21 10:18 UTC, merged