Kurzdoku von Mejri und Jakupi hinzugefügt
th-koeln/mi-bachelor-screendesign-projekte pull request #39
Opened 2021-03-21 22:10 UTC by dalilame

2021-03-21 22:17 UTC, finnge requested changes
Einrückungsfehler in der Markdown-Datei. Bitte eindeutige Benamung aller Dateien!

````
{nachname1}-{nachname2}-{artefakt}.{ext}
````

Bspw.

```
jakupi-mejri-bild1.png
jakupi-mejri.md
```

Auch die Reihenfolge von den Nachnamen beibehalten.

[Erklärung von GitHub wie Dateinamen umbenannt werden können](https://docs.github.com/en/github/managing-files-in-a-repository/renaming-a-file)

2021-03-21 22:17 UTC, finnge commented on _kurzdokus/SD-2020/Mejri-Jakupi.md
> +      -Egzona Jakupi
```suggestion
  - Dalila Mejri
  - Egzona Jakupi
```

2021-03-21 22:17 UTC, finnge commented on _kurzdokus/SD-2020/Mejri-Jakupi.md
> +      -Jakupi1-Mejri2-Bild.8.png
```suggestion
  - Mejri-Jakupi-Bild9.png
  - Mejri-Jakupi-Bild11.png
  - Mejri-Jakupi-Bild13.png
  - Jakupi1-Mejri2-Bild.6.png
  - Jakupi1-Mejri2-Bild.8.png
```

2021-03-21 22:28 UTC, dalilame commented
Ist es ok jetzt?

2021-03-21 22:40 UTC, dalilame commented
Ausserdem können wir keinen Termin mehr für die Prüfung, im Ilias buchen.

2021-03-21 22:45 UTC, finnge commented
> Ausserdem können wir keinen Termin mehr für die Prüfung, im Ilias buchen.

Dazu bitte die Antwort im Ilias beachten

2021-03-21 22:46 UTC, dalilame commented
Ist es ok jetzt oder sind noch Fehler da? 
Dankeschön

2021-03-21 22:46 UTC, finnge requested changes
Neben den Makierten Fehlern sind die Dateien immer noch falsch benannt.

2021-03-21 22:46 UTC, finnge commented on _kurzdokus/SD-2020/Mejri-Jakupi.md
> +-Egzona Jakupi
```suggestion
- Dalila Mejri
- Egzona Jakupi
```

2021-03-21 22:46 UTC, finnge commented on _kurzdokus/SD-2020/Mejri-Jakupi.md
> +-Jakupi1-Mejri2-Bild.6.png
```suggestion
- Mejri-Jakupi-Bild9.png
- Mejri-Jakupi-Bild11.png
- Mejri-Jakupi-Bild13.png 
- Jakupi1-Mejri2-Bild.1.png
- Jakupi1-Mejri2-Bild.6.png
```

2021-03-22 09:35 UTC, finnge commented
@dalilame Leider habt Ihr noch ein paar Fehler in den Dateinamen der Bilder. Hier die Dateien, die Ihr ändern solltet:

---
Im Ordner `_kurzdokus/sd-2020`
```diff
- Jakupi1-Mejri2-bild.1.png.png
+ jakupi-mejri-bild1.png
- Jakupi1-Mejri2-bild.2.png.png
+ jakupi-mejri-bild2.png
- Jakupi1-Mejri2-bild.3.png.png
+ jakupi-mejri-bild3.png
- Jakupi1-Mejri2-bild.4.png.png
+ jakupi-mejri-bild4.png
````
usw. 

Ihr habt in fast allen Dateinamen eine doppelte Dateiendung. Diese bitte entfehrnen.

Achtet darauf dass die Reihenfolge von den beiden Nachnamen immer die gleiche ist.

---

How To: https://docs.github.com/en/github/managing-files-in-a-repository/renaming-a-file

Ihr habt Bilder in das Hauptverzeichnis eingefügt. Diese bitte löschen.

How To: https://docs.github.com/en/github/managing-files-in-a-repository/deleting-files-in-a-repository

---

Wenn ihr das alles gemacht habt müssen die Dateinamen in der Markdown-Datei mit denen im Dateiverzeichnis übereinstimmen.

2021-03-22 13:37 UTC, finnge commented
Hier ein friendly reminder.
Kann ich euch irgendwie weiterhelfen?

2021-03-22 15:52 UTC, dalilame commented
Hallo Entschuldigung für die späte Rückmeldung wir mussten leider Arbeiten. 
Wir haben nun die Bilder gelöscht. 
Unser Problem besteht darin das wir die Namen der Dateien nicht ändern können.

2021-03-22 17:05 UTC, dalilame commented
Ist es jetzt so richtig? VG

2021-03-22 17:16 UTC, finnge requested changes
Noch ein paar Fehler in der Markdown-Datei

2021-03-22 17:16 UTC, finnge commented on _kurzdokus/SD-2020/jakupi-mejri.md
> +gallerie:
```suggestion
gallery:
```

2021-03-22 17:16 UTC, finnge commented on _kurzdokus/SD-2020/jakupi-mejri.md
> +teaserimage: jakupi-mejri-teaser.png
Es gibt keine Datei die so heißt. Vllt vergessen hochzuladen

2021-03-22 17:17 UTC, finnge commented on _kurzdokus/SD-2020/jakupi-mejri.md
> +teaserimage: jakupi-mejri-teaser.png
Also es fehlt die `jakupi-mejri-teaser.png`

2021-03-22 18:49 UTC, dalilame commented
ohh sorry, es ist jetzt hochgeladen.. Danke für deine Hilfe ich hoffe dieses mal ist alles ok! :)

2021-03-22 19:29 UTC, finnge approved these changes

2021-03-22 19:30 UTC, merged